import { useState } from 'react';
import { FileText, Download, Copy, Sparkles, FileCheck, Languages, Scale } from 'lucide-react';
import { Button } from '../ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';
import { Label } from '../ui/label';
import { Badge } from '../ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';

interface DraftingTabProps {
  matterId: string;
}

export function DraftingTab({ matterId }: DraftingTabProps) {
  const [documentType, setDocumentType] = useState('');
  const [language, setLanguage] = useState('english');
  const [styleFormat, setStyleFormat] = useState('hc-malaysia');
  const [instructions, setInstructions] = useState('');
  const [generatedContent, setGeneratedContent] = useState('');

  const documentTypes = [
    { value: 'statement-claim', label: 'Statement of Claim' },
    { value: 'statement-defence', label: 'Statement of Defence' },
    { value: 'affidavit', label: 'Affidavit in Support' },
    { value: 'witness-statement', label: 'Witness Statement' },
    { value: 'submission', label: 'Written Submission' },
    { value: 'bundle-authorities', label: 'Bundle of Authorities (Cover)' },
    { value: 'case-management', label: 'Case Management Checklist' },
    { value: 'letter-court', label: 'Letter to Court' },
    { value: 'letter-counsel', label: 'Letter to Opposing Counsel' },
  ];

  const styleFormats = [
    { value: 'hc-malaysia', label: 'High Court - Malaysia', description: 'Rules of Court 2012 formatting' },
    { value: 'coa-malaysia', label: 'Court of Appeal - Malaysia', description: 'Appellate procedures' },
    { value: 'fc-malaysia', label: 'Federal Court - Malaysia', description: 'Federal Court Rules' },
    { value: 'subordinate-malaysia', label: 'Subordinate Courts - Malaysia', description: 'Sessions/Magistrates formatting' },
    { value: 'hc-india', label: 'High Court - India', description: 'CPC formatting' },
  ];

  const templates = [
    {
      name: 'Commercial Dispute Template',
      description: 'Pre-filled structure for breach of contract claims',
      type: 'statement-claim',
    },
    {
      name: 'Employment Termination Defence',
      description: 'Standard defence for wrongful dismissal',
      type: 'statement-defence',
    },
    {
      name: 'Judicial Review Application',
      description: 'O. 53 format for JR applications',
      type: 'submission',
    },
  ];

  const handleGenerate = () => {
    // Simulate AI generation
    setGeneratedContent(`IN THE HIGH COURT OF MALAYA AT KUALA LUMPUR
(CIVIL DIVISION)

ORIGINATING SUMMONS NO: WA-22NCVC-145-10/2024

BETWEEN

TAN SRI LIM CHEE HWA ... PLAINTIFF

AND

ABC CORPORATION SDN BHD ... DEFENDANT

_________________________________________________________________

STATEMENT OF CLAIM
_________________________________________________________________

1. The Plaintiff is an individual businessman carrying on business under the name and style of "Lim Industries" with its principal place of business at No. 123, Jalan Sultan Ismail, 50250 Kuala Lumpur.

2. The Defendant is a company incorporated under the Companies Act 2016 and having its registered office at No. 456, Jalan Ampang, 50450 Kuala Lumpur.

[This is a placeholder generated content demonstrating the Malaysian court formatting style with proper numbering, spacing, and legal terminology. In a real implementation, this would be generated by AI based on the case facts and user instructions.]

3. At all material times, the Plaintiff and Defendant were parties to a written agreement dated 15 March 2023 ("the Agreement") whereby the Defendant agreed to supply certain goods to the Plaintiff.

4. It was an express term of the Agreement that:
   (a) The Defendant shall deliver the goods within 30 days from the date of order;
   (b) The goods shall be of merchantable quality; and
   (c) Payment shall be made within 60 days from delivery.

...

DATED this 28th day of October 2025.

_________________________
[Counsel's Name]
Counsel for the Plaintiff
`);
  };

  return (
    <div className="p-4 lg:p-6">
      <Tabs defaultValue="generate" className="space-y-6">
        <TabsList>
          <TabsTrigger value="generate" className="gap-2">
            <Sparkles className="h-4 w-4" />
            Generate Draft
          </TabsTrigger>
          <TabsTrigger value="templates" className="gap-2">
            <FileCheck className="h-4 w-4" />
            Templates
          </TabsTrigger>
          <TabsTrigger value="citation" className="gap-2">
            <Scale className="h-4 w-4" />
            Citation Helper
          </TabsTrigger>
        </TabsList>

        <TabsContent value="generate" className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Configuration Panel */}
            <Card>
              <CardHeader>
                <CardTitle>Document Configuration</CardTitle>
                <CardDescription>
                  Select document type and formatting preferences
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="doc-type">Document Type</Label>
                  <Select value={documentType} onValueChange={setDocumentType}>
                    <SelectTrigger id="doc-type">
                      <SelectValue placeholder="Select document type" />
                    </SelectTrigger>
                    <SelectContent>
                      {documentTypes.map((type) => (
                        <SelectItem key={type.value} value={type.value}>
                          {type.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="style">Court Style & Format</Label>
                  <Select value={styleFormat} onValueChange={setStyleFormat}>
                    <SelectTrigger id="style">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {styleFormats.map((format) => (
                        <SelectItem key={format.value} value={format.value}>
                          <div>
                            <p>{format.label}</p>
                            <p className="text-xs text-slate-500">{format.description}</p>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="language">Language</Label>
                  <Select value={language} onValueChange={setLanguage}>
                    <SelectTrigger id="language">
                      <Languages className="h-4 w-4 mr-2" />
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="english">English</SelectItem>
                      <SelectItem value="malay">Bahasa Malaysia</SelectItem>
                      <SelectItem value="bilingual">Bilingual (Side-by-side)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="instructions">Instructions & Context</Label>
                  <Textarea
                    id="instructions"
                    placeholder="Provide specific instructions, facts to include, or arguments to make..."
                    value={instructions}
                    onChange={(e) => setInstructions(e.target.value)}
                    className="min-h-[120px]"
                  />
                </div>

                <div className="pt-2">
                  <Button onClick={handleGenerate} className="w-full gap-2">
                    <Sparkles className="h-4 w-4" />
                    Generate Draft
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Preview/Output Panel */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Generated Draft</CardTitle>
                    <CardDescription>
                      Malaysian court formatting with proper citations
                    </CardDescription>
                  </div>
                  {generatedContent && (
                    <div className="flex gap-2">
                      <Button size="icon" variant="ghost">
                        <Copy className="h-4 w-4" />
                      </Button>
                      <Button size="icon" variant="ghost">
                        <Download className="h-4 w-4" />
                      </Button>
                    </div>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                {generatedContent ? (
                  <div className="bg-white border rounded-lg p-6 min-h-[400px] overflow-auto">
                    <pre className="whitespace-pre-wrap text-sm text-slate-900 font-mono">
                      {generatedContent}
                    </pre>
                  </div>
                ) : (
                  <div className="border-2 border-dashed rounded-lg p-12 text-center min-h-[400px] flex items-center justify-center">
                    <div>
                      <FileText className="h-12 w-12 text-slate-300 mx-auto mb-4" />
                      <p className="text-sm text-slate-600">
                        Configure options and click Generate to create a draft
                      </p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="templates" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Firm Templates</CardTitle>
              <CardDescription>
                Pre-configured templates tailored to your practice
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {templates.map((template, index) => (
                  <Card key={index} className="hover:shadow-md transition-shadow cursor-pointer">
                    <CardContent className="pt-4">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1">
                          <h4 className="text-slate-900 mb-1">{template.name}</h4>
                          <p className="text-sm text-slate-600">{template.description}</p>
                          <Badge variant="outline" className="mt-2">
                            {documentTypes.find(t => t.value === template.type)?.label}
                          </Badge>
                        </div>
                        <Button size="sm">Use Template</Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
                <Button variant="outline" className="w-full">
                  Upload New Template
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="citation" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Malaysian Citation Generator</CardTitle>
              <CardDescription>
                Generate properly formatted case law and legislation citations
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Case Name</Label>
                <input
                  type="text"
                  placeholder="e.g., Tan Sri Khoo Teck Puat v Plenitude Holdings"
                  className="w-full px-3 py-2 border rounded-md"
                />
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>Year</Label>
                  <input type="text" placeholder="2024" className="w-full px-3 py-2 border rounded-md" />
                </div>
                <div className="space-y-2">
                  <Label>Volume</Label>
                  <input type="text" placeholder="5" className="w-full px-3 py-2 border rounded-md" />
                </div>
                <div className="space-y-2">
                  <Label>Report</Label>
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="MLJ/CLJ" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="mlj">MLJ</SelectItem>
                      <SelectItem value="clj">CLJ</SelectItem>
                      <SelectItem value="amr">AMR</SelectItem>
                      <SelectItem value="mlra">MLRA</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label>Page</Label>
                <input type="text" placeholder="123" className="w-full px-3 py-2 border rounded-md" />
              </div>
              <div className="pt-2 bg-slate-50 p-4 rounded-lg">
                <p className="text-xs text-slate-600 mb-2">Generated Citation:</p>
                <p className="text-sm text-slate-900">
                  <em>Tan Sri Khoo Teck Puat v Plenitude Holdings</em> [2024] 5 MLJ 123
                </p>
              </div>
              <Button className="w-full">Copy Citation</Button>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
